/**
 * This SDK against the Rust one, byte for byte.
 *
 * `spec/wire-vectors.json` is generated by `cargo test -p clob-client --test wire_vectors`
 * and is the contract: Rust asserts the file still describes what it produces, and this
 * asserts the same arguments produce the same bytes here. Neither implementation can move
 * without the other failing.
 *
 * Every case is built from the named inputs in the file rather than from its own answer,
 * so the account list — its order, and every signer and writable flag — is under test
 * too, not just the data.
 */

import { test } from "node:test";
import assert from "node:assert/strict";

import vectors from "../../../spec/wire-vectors.json" with { type: "json" };
import * as ix from "../src/instructions.ts";
import type { Instruction, MarketAddresses, OrderId, OrderPacket } from "../src/types.ts";
import { PostOnlyRejection, SelfTradeBehavior, Side, SizeClass } from "../src/types.ts";

const inputs = vectors.inputs;

const market: MarketAddresses = {
  programAddress: inputs.programAddress,
  market: inputs.market,
  baseVault: inputs.baseVault,
  quoteVault: inputs.quoteVault,
  vaultSigner: inputs.vaultSigner,
  tokenProgram: inputs.tokenProgram,
};

const receipt = {
  logAuthority: inputs.logAuthority,
  logAuthorityBump: inputs.logAuthorityBump,
};

const { trader, traderBase, traderQuote } = inputs;

function hex(bytes: Uint8Array): string {
  return [...bytes].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}

/** An order ID as the fixture writes one: two decimal strings. */
function orderId(raw: { priceInTicks: string; orderSequenceNumber: string }): OrderId {
  return {
    priceInTicks: BigInt(raw.priceInTicks),
    orderSequenceNumber: BigInt(raw.orderSequenceNumber),
  };
}

const SIDES: Record<string, Side> = { bid: Side.Bid, ask: Side.Ask };
const REJECTIONS: Record<string, PostOnlyRejection> = {
  reject: PostOnlyRejection.Reject,
  slide: PostOnlyRejection.Slide,
};

/**
 * Builds the instruction a case names, from that case's arguments.
 *
 * The dispatch is written out rather than derived. A generated one would share whatever
 * assumption the encoder makes, and two things making the same mistake agree perfectly.
 */
// deno-lint-ignore-next-line no-explicit-any -- fixture arguments are checked by the assert
function build(name: string, args: any): Instruction {
  switch (name) {
    case "claimSeat":
      return ix.claimSeat(market, trader);
    case "evictSeat":
      return ix.evictSeat(market, trader);
    case "deposit":
      return ix.deposit(
        market,
        trader,
        traderBase,
        traderQuote,
        BigInt(args.baseLots),
        BigInt(args.quoteLots),
      );
    case "withdraw":
      return ix.withdraw(
        market,
        trader,
        traderBase,
        traderQuote,
        BigInt(args.baseLots),
        BigInt(args.quoteLots),
      );
    case "limit":
      return ix.placeOrder(
        market,
        trader,
        ix.limit(SIDES[args.side]!, BigInt(args.priceInTicks), BigInt(args.baseLots)),
      );
    case "limitWithReceipt":
      return ix.placeOrder(
        market,
        trader,
        ix.limit(SIDES[args.side]!, BigInt(args.priceInTicks), BigInt(args.baseLots)),
        receipt,
      );
    case "postOnlyReject":
    case "postOnlySlide":
      return ix.placeOrder(
        market,
        trader,
        ix.postOnly(
          SIDES[args.side]!,
          BigInt(args.priceInTicks),
          BigInt(args.baseLots),
          REJECTIONS[args.rejection]!,
        ),
      );
    case "fillOrKill":
      return ix.placeOrder(
        market,
        trader,
        ix.fillOrKill(SIDES[args.side]!, BigInt(args.priceInTicks), BigInt(args.baseLots)),
      );
    case "marketOrder":
      return ix.placeOrder(
        market,
        trader,
        ix.marketOrder(SIDES[args.side]!, BigInt(args.baseLots), args.matchLimit),
      );
    case "cancelOrder":
      return ix.cancelOrder(market, trader, orderId(args));
    case "reduceOrder":
      return ix.reduceOrder(market, trader, orderId(args), BigInt(args.baseLots));
    case "cancelAllOrders":
      return ix.cancelAllOrders(market, trader, SIDES[args.side]!, args.limit);
    case "batchUpdate":
    case "batchUpdateEmpty": {
      const packets: OrderPacket[] = args.orders.map((order: any) =>
        ix.postOnly(
          SIDES[order.side]!,
          BigInt(order.priceInTicks),
          BigInt(order.baseLots),
          REJECTIONS[order.rejection]!,
        ),
      );
      return ix.batchUpdate(market, trader, args.cancels.map(orderId), packets);
    }
    case "swap":
      return ix.swap(market, trader, traderBase, traderQuote, {
        side: SIDES[args.side]!,
        priceInTicks: BigInt(args.priceInTicks),
        baseLots: BigInt(args.baseLots),
        minBaseLotsToFill: BigInt(args.minBaseLotsToFill),
        matchLimit: args.matchLimit,
      });
    case "collectFees":
      return ix.collectFees(market, inputs.feeRecipient);
    case "initializeMarket":
      return ix.initializeMarket(market, {
        baseMint: inputs.baseMint,
        quoteMint: inputs.quoteMint,
        authority: inputs.authority,
        feeRecipient: inputs.feeRecipient,
        sizeClass: SizeClass.Small,
        baseLotsPerBaseUnit: BigInt(args.baseLotsPerBaseUnit),
        tickSizeInQuoteLotsPerBaseUnit: BigInt(args.tickSizeInQuoteLotsPerBaseUnit),
        baseAtomsPerBaseLot: BigInt(args.baseAtomsPerBaseLot),
        quoteAtomsPerQuoteLot: BigInt(args.quoteAtomsPerQuoteLot),
        takerFeeBps: BigInt(args.takerFeeBps),
        vaultSignerBump: vaultSignerBump(),
      });
    default:
      throw new Error(`no builder mapped for the case "${name}"`);
  }
}

/**
 * The bump the fixture's `initializeMarket` was built with, read back out of its bytes.
 *
 * Derivation needs an on-curve check this SDK deliberately does not ship, and the value
 * is a caller's input everywhere else — `create-market` finds it once and records it in
 * the account.
 */
function vaultSignerBump(): number {
  const initialize = vectors.instructions.find((c) => c.name === "initializeMarket")!;
  const bytes = initialize.data;
  return parseInt(bytes.slice(-2), 16);
}

for (const expected of vectors.instructions) {
  test(`${expected.name} encodes exactly as Rust does`, () => {
    const actual = build(expected.name, expected.args);

    assert.equal(hex(actual.data), expected.data, "instruction data");
    assert.equal(actual.programAddress, expected.programAddress, "program");
    assert.deepEqual(
      actual.accounts.map((a) => ({ ...a })),
      expected.accounts.map((a) => ({ ...a })),
      "accounts, in order, with their flags",
    );
  });
}

test("every case in the file is covered", () => {
  // A case the dispatch does not know about would otherwise be skipped in silence, which
  // is the failure mode of a conformance suite that grows on only one side.
  for (const expected of vectors.instructions) {
    assert.doesNotThrow(
      () => build(expected.name, expected.args),
      `case "${expected.name}" is in the vectors but not built here`,
    );
  }
  assert.ok(vectors.instructions.length >= 18, "the fixture lost cases");
});

test("the constants agree", () => {
  const { sides, postOnlyRejections, selfTradeBehaviors, sizeClasses } = vectors.constants;
  assert.equal(Side.Bid, sides.bid);
  assert.equal(Side.Ask, sides.ask);
  assert.equal(PostOnlyRejection.Reject, postOnlyRejections.reject);
  assert.equal(PostOnlyRejection.Slide, postOnlyRejections.slide);
  assert.equal(SelfTradeBehavior.DecrementTake, selfTradeBehaviors.decrementTake);
  assert.equal(SelfTradeBehavior.CancelProvide, selfTradeBehaviors.cancelProvide);
  assert.equal(SelfTradeBehavior.Abort, selfTradeBehaviors.abort);
  assert.equal(SizeClass.Small, sizeClasses.small);
  assert.equal(SizeClass.Medium, sizeClasses.medium);
  assert.equal(SizeClass.Large, sizeClasses.large);
});
